web_app/homepage/urls.py
from django.conf.urls import url
from homepage import views

app_name = 'homepage'

urlpatterns = [
    url(r'^time/$', views.time, name='_time'),
    url(r'^$', views.index, name='_index'),
]

web_app/products/urls.py
from django.conf.urls import url
from . import views

app_name = 'products'

urlpatterns = [
    url(r'^addproduct/$', views.product_create, name="addproduct"),
    url(r'^products/$', views.list_of_products, name="list_of_product"),
]

web_app/web_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^homepage/',include('homepage.urls')),
    url(r'^products/',include('products.urls')),
    url(r'admin/', admin.site.urls),
]

web_app/homepage/models.py
from django.db import models

web_app/products/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
   category_name = models.CharField(max_length=40)
   category_slug = models.SlugField(unique=True)
   
   def __str__(self):
       return self.category_name


class products(models.Model):
    Category_title = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=20)
    slug = models.SlugField(unique=True)
    product_price = models.IntegerField(default=100)
    product_description = models.CharField(max_length=500)
    product_rating = models.IntegerField(default=5)
    product_quantity = models.IntegerField(default=10)

    def __str__(self):
        return self.product_name

web_app/user_app/models.py
from django.db import models
from products.models import products
# Create your models here.


class User_Address(models.Model):
    line1 = models.CharField(max_length=150)
    line2 = models.CharField(max_length=150)
    postalcode = models.CharField(max_length=10)
    city = models.CharField(max_length=150)
    country = models.CharField(max_length=150)

class User_Credential(models.Model):
    user_id = models.IntegerField(primary_key=True)
    user_name = models.CharField(max_length=15)
    user_password = models.CharField(max_length=15)
    user_email = models.EmailField(unique=True)
    user_mobile = models.IntegerField(unique=True)
    user_address = models.ForeignKey(User_Address, on_delete=models.CASCADE)
    user_register_date = models.DateTimeField(auto_now_add=True)

class User_Card_Details(models.Model):
    user_id = models.ForeignKey(User_Credential, on_delete=models.CASCADE)
    user_credit_card = models.IntegerField(unique=True)
    user_credit_card_expiry_month = models.IntegerField()
    user_credit_card_expiry_year = models.IntegerField()
    user_debit_card = models.IntegerField(unique=True)
    user_debit_card_expiry_year = models.IntegerField()
    user_debit_card_expiry_year = models.IntegerField()

class User_Login_Logout_details(models.Model):
    user_id = models.ForeignKey(User_Credential, on_delete=models.CASCADE)
    user_login_timestamp = models.DateTimeField(auto_now_add=True)
    user_logout_timestamp = models.DateTimeField(auto_now_add=True)

class User_Wishlist(models.Model):
    user_id = models.ForeignKey(User_Credential, on_delete=models.CASCADE)
    product_id = models.ForeignKey(products, on_delete=models.CASCADE)

web_app/homepage/forms.py
from django import forms

class ProductsForm(forms.Form):
    product_name = forms.CharField(max_length=100)
    product_description = forms.CharField()
    product_slug = forms.SlugField()  
    product_price = forms.CharField()
    product_rating = forms.CharField()
    product_quantity = forms.CharField()

    def clean_name(self):
        name = self.cleaned_data['product_name']
        if name == 'djangobin' or name == 'DJANGOBIN':
            raise ValidationError("name can't be {}.".format(name))
 
        # Always return the data
        return name
 
    def clean_slug(self):
        return self.cleaned_data['slug'].lower()
 
    def clean(self):
        cleaned_data = super(LanguageForm, self).clean()
        slug = cleaned_data.get('slug')
        mime = cleaned_data.get('mime')
 
        if slug == mime:
            raise ValidationError("Slug and MIME shouldn't be same.")
 
        # Always return the data
        return cleaned_data

web_app/products/forms.py
from django import forms
from . import models

class AddProduct(forms.ModelForm):
  class Meta:
    model = models.products
    fields = ['product_name','slug','product_price','product_description','product_rating','product_quantity','Category_title']

web_app/homepage/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from datetime import datetime
# Create your views here.

def index(request):
  return HttpResponse("Hello django")

def time(request):
  now = datetime.now()
  return render(request,'homepage/index.html', {'now': now })
  #using render method from shortcuts module return render(request,'homepage/index.html', {'now': now })#
  #using render_to_response from shortcuts module(NOTE:Its depricated now) return render_to_response('homepage/index.html', {'now': now })#

web_app/products/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . import forms
from products.models import products , Category

# Create your views here.


def product_create(request):
    if request.method == "POST":
      form = forms.AddProduct(request.POST)  
      #reqest.files for the file upload
      #save product to the database
      form.save()
      product = products.objects.all()
      return render(request,'product/products.html',{'product':product})
    else:
      form = forms.AddProduct()
      category = Category.objects.all()
      categories_context = {
        'category_name' : category,
        'form' : form,
        }

    return render(request,'product/addproduct.html',categories_context)

def list_of_products(request):
   product = products.objects.all()
   print(product)
   return render(request,'product/products.html',{'product':product})

def update_products(request):
   form = forms.AddProduct()
   return render(request,'product/addproduct.html',{'from':form})  

web_app/user_app/views.py
from django.shortcuts import render

# Create your views here.

web_app/homepage/templates/homepage/index.html
{% extends "_base.html" %}

{% block pagehead %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block page_content %}
  <section id="products-wrapper">
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="1" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="2" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="2" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="4" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="1" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="2" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="2" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="4" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="1" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="2" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="2" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
    {% include "/home/rashmi/Desktop/web_app/web_app/products/templates/product/_product-card.html" with product_name="product_name" product_price="4" product_card_description="Lorem Ipsum is simply dummy text of the printing and typesetting industry." %}
  </section>
{% endblock %}

{% block footer %}
    
{% endblock %}

web_app/homepage/templates/homepage/nav.html
<nav>
    <a href="#">Home</a>
    <a href="#">blog</a>
    <a href="#">Contact</a>
    <a href="#">Career</a>
</nav>

web_app/products/templates/_base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}The Great Django Blog{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="/static/css/common.css">
  {% block pagehead %}
    <!-- To include css,js or to link something in head -->
  {% endblock %}
</head>
<body>
    {% block page_content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
    <script src="/static/js/main.js"></script>
</body>
</html>

web_app/products/templates/product/_base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}The Great Django Blog{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="/static/css/common.css">
  {% block pagehead %}
    <!-- To include css,js or to link something in head -->
  {% endblock %}
</head>
<body>
    {% block page_content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
    <script src="/static/js/main.js"></script>
</body>
</html>

web_app/products/templates/product/_product-card.html
<div class="card-wrapper">
  <div class="card-image">
    <i class="product-card-whishlist fa fa-heart"></i>
    <img src="https://images-eu.ssl-images-amazon.com/images/G/31/img17/Home/LA/CatTiles/new/musruthi_2018-02-14T07-54_c3a1c0_1099842_670x700-7._CB502681521_.jpg" alt="">
  </div>
  <div class="card-description">
    <div class="product-title"><h4 class="card-heading">{{product_name}} {{product_price}}</h4> <div class="product-card-rating" ><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-empty"></i></div></div>
    <p class="product-card-description">{{product_card_description}}</p>
  </div>
</div>

web_app/products/templates/product/_product-category-nav.html
  <section id="products-menu-nav">
    <h2 class="menu-heading">Categories</h2>
    <div id="product-categories-wrapper">
      <ul class="categories">
        <li class="btn active" onclick="filterSelection('all')">ALL</li>
        <li class="btn" onclick="filterSelection('women')">WOMAN</li>
        <li class="btn" onclick="filterSelection('man')">MAN</li>
        <li class="btn" onclick="filterSelection('accessories')">ACCESSORIES</li>
        <li class="btn" onclick="filterSelection('shoes')">SHOES</li>
        <li class="btn" onclick="filterSelection('accessories')">ACCESSORIES</li>
      </ul>
    </div>
  </section>

web_app/products/templates/product/addproduct.html
{% extends "_base.html" %}

{% block pagehead %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block page_content %}
   <section id="products-wrapper">
      <form class="product-form" action="{% url 'products:addproduct' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Addproduct">
      </form>
   </section>
{% endblock %}

{% block footer %}

{% endblock %}

web_app/products/templates/product/products.html
{% extends "_base.html" %}

{% block pagehead %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block page_content %}
   <section id="">
     {% for product in product %}
     <p>{{product}}</p>
     {% endfor %}
   </section>
    </hr>
{% endblock %}

{% block footer %}

{% endblock %}

web_app/templates/_base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}The Great Django Blog{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="/static/css/common.css">
  {% block pagehead %}
    <!-- To include css,js or to link something in head -->
  {% endblock %}
</head>
<body>
    {% block page_content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
    <script src="/static/js/main.js"></script>
</body>
</html>

web_app/templates/components/_product-card.html
<div class="card-wrapper">
  <div class="card-image">
    <i class="product-card-whishlist fa fa-heart"></i>
    <img src="https://images-eu.ssl-images-amazon.com/images/G/31/img17/Home/LA/CatTiles/new/musruthi_2018-02-14T07-54_c3a1c0_1099842_670x700-7._CB502681521_.jpg" alt="">
  </div>
  <div class="card-description">
    <div class="product-title"><h4 class="card-heading">{{product_name}} {{product_price}}</h4> <div class="product-card-rating" ><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-empty"></i></div></div>
    <p class="product-card-description">{{product_card_description}}</p>
  </div>
</div>

web_app/templates/components/_product-category-nav.html
  <section id="products-menu-nav">
    <h2 class="menu-heading">Categories</h2>
    <div id="product-categories-wrapper">
      <ul class="categories">
        <li class="btn active" onclick="filterSelection('all')">ALL</li>
        <li class="btn" onclick="filterSelection('women')">WOMAN</li>
        <li class="btn" onclick="filterSelection('man')">MAN</li>
        <li class="btn" onclick="filterSelection('accessories')">ACCESSORIES</li>
        <li class="btn" onclick="filterSelection('shoes')">SHOES</li>
        <li class="btn" onclick="filterSelection('accessories')">ACCESSORIES</li>
      </ul>
    </div>
  </section>